common: &common
        adapter: mysql
        encoding: utf8
        reconnect: false
        pool: 5
        username: root
        password: root
        socket: /var/run/mysqld/mysqld.sock

#Genlinux customized database configuration
development:
       database: webt_development
       <<: *common

